name: CD

on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Create .env file
        working-directory: ./backend
        run: |
          cat <<EOF > .env
          PORT='${{ secrets.PORT }}'
          DB_HOST='${{ secrets.DB_HOST }}'
          DB_PORT='${{ secrets.DB_PORT }}'
          DB_USER='${{ secrets.DB_USER }}'
          DB_PASSWORD='${{ secrets.DB_PASSWORD }}'
          DB_NAME='${{ secrets.DB_NAME }}'
          OPENID_CLIENT_ID='${{ secrets.OPENID_CLIENT_ID }}'
          OPENID_CLIENT_SECRET='${{ secrets.OPENID_CLIENT_SECRET }}'
          OPENID_ENDPOINT='${{ secrets.OPENID_ENDPOINT }}'
          SMS_SANDBOX_API_KEY='${{ secrets.SMS_SANDBOX_API_KEY }}'
          SMS_SANDBOX_API_USERNAME='${{ secrets.SMS_SANDBOX_API_USERNAME }}'
          EOF

      - name: Build
        working-directory: ./backend
        run: make build

      - name: Deploy to App Engine
        working-directory: ./backend
        run: |
          gcloud app deploy --quiet
