name: CD

on:
  workflow_run:
    workflows: [ "CI" ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          export_default_credentials: true

      - name: Build
        working-directory: ./backend
        run: make build

      - name: Set environment variables in app.yaml
        run: |
          sed -i "s/^  PORT:.*$/  PORT: '${{ secrets.PORT }}'/" app.yaml
          sed -i "s/^  DB_HOST:.*$/  DB_HOST: '${{ secrets.DB_HOST }}'/" app.yaml
          sed -i "s/^  DB_PORT:.*$/  DB_PORT: '${{ secrets.DB_PORT }}'/" app.yaml
          sed -i "s/^  DB_USER:.*$/  DB_USER: '${{ secrets.DB_USER }}'/" app.yaml
          sed -i "s/^  DB_PASSWORD:.*$/  DB_PASSWORD: '${{ secrets.DB_PASSWORD }}'/" app.yaml
          sed -i "s/^  DB_NAME:.*$/  DB_NAME: '${{ secrets.DB_NAME }}'/" app.yaml
          sed -i "s/^  OPENID_CLIENT_ID:.*$/  OPENID_CLIENT_ID: '${{ secrets.OPENID_CLIENT_ID }}'/" app.yaml
          sed -i "s/^  OPENID_CLIENT_SECRET:.*$/  OPENID_CLIENT_SECRET: '${{ secrets.OPENID_CLIENT_SECRET }}'/" app.yaml
          sed -i "s/^  OPENID_ENDPOINT:.*$/  OPENID_ENDPOINT: '${{ secrets.OPENID_ENDPOINT }}'/" app.yaml
          sed -i "s/^  SMS_SANDBOX_API_KEY:.*$/  SMS_SANDBOX_API_KEY: '${{ secrets.SMS_SANDBOX_API_KEY }}'/" app.yaml
          sed -i "s/^  SMS_SANDBOX_API_USERNAME:.*$/  SMS_SANDBOX_API_USERNAME: '${{ secrets.SMS_SANDBOX_API_USERNAME }}'/" app.yaml

      - name: Deploy to App Engine
        run: |
          gcloud app deploy --quiet
