name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Test
        working-directory: ./backend
        run: make test

      - name: Coverage
        working-directory: ./backend
        run: make coverage

      - name: Clean
        working-directory: ./backend
        run: make clean